// ═══════════════════════════════════════════════
// INTERVIEW QUESTION BANK — 200+ questions
// Tags: topic, difficulty, company-type
// ═══════════════════════════════════════════════
const QUESTIONS = [
// ── JavaScript ───────────────────────────────
{id:'js001',q:'What is the difference between var, let, and const?',hint:'Cover scope (function vs block), hoisting, and temporal dead zone. var is function-scoped and hoisted; let/const are block-scoped. const prevents reassignment but not mutation.',tags:['js','easy'],cat:'JavaScript'},
{id:'js002',q:'Explain the JavaScript event loop. What are the call stack, task queue, and microtask queue?',hint:'Call stack runs synchronous code. Microtasks (Promises, queueMicrotask) run before each task queue item. Task queue holds setTimeout, setInterval, DOM events. This is why Promise.then fires before setTimeout even with 0ms delay.',tags:['js','hard'],cat:'JavaScript'},
{id:'js003',q:'What is a closure? Give a real-world use case.',hint:'A closure is a function that remembers variables from its outer scope even after the outer function has returned. Real use: debounce functions, private variables via module pattern, memoization.',tags:['js','med'],cat:'JavaScript'},
{id:'js004',q:'What is the difference between == and ===?',hint:'== uses type coercion (0 == "0" is true). === checks type and value strictly. Always use === in production code. Know the coercion rules for interviews.',tags:['js','easy'],cat:'JavaScript'},
{id:'js005',q:'Explain Promise.all, Promise.allSettled, Promise.race, and Promise.any.',hint:'all: rejects if any rejects. allSettled: waits for all, returns array of results+reasons. race: resolves/rejects with first settled. any: resolves with first fulfilled, rejects only if all reject.',tags:['js','med'],cat:'JavaScript'},
{id:'js006',q:'What is debounce? What is throttle? Implement debounce from scratch.',hint:'Debounce delays execution until after N ms of inactivity (search input). Throttle limits to once per N ms (scroll handler). Debounce: function(fn,ms){let t;return function(){clearTimeout(t);t=setTimeout(()=>fn.apply(this,arguments),ms)}}',tags:['js','med'],cat:'JavaScript'},
{id:'js007',q:'What is prototypal inheritance in JavaScript?',hint:'Every object has [[Prototype]] chain. Object.create, __proto__, Object.getPrototypeOf. Class syntax is sugar over prototypal inheritance. Contrast with classical inheritance.',tags:['js','med'],cat:'JavaScript'},
{id:'js008',q:'Explain async/await. How does it differ from raw Promises?',hint:'async/await is syntactic sugar over Promises. await pauses execution of the async function (not the whole thread). Error handling with try/catch vs .catch(). Sequential vs parallel with Promise.all.',tags:['js','easy'],cat:'JavaScript'},
{id:'js009',q:'What are WeakMap and WeakSet? When would you use them?',hint:'Hold weak references — GC can collect keys if no other references exist. Use for caching metadata about DOM nodes or objects without preventing GC. Cannot be iterated.',tags:['js','hard'],cat:'JavaScript'},
{id:'js010',q:'Explain event delegation. Why is it better than attaching listeners to each element?',hint:'Attach one listener to a parent, use e.target to detect which child was clicked. Works for dynamically added elements. Fewer event listeners = better performance.',tags:['js','med'],cat:'JavaScript'},
{id:'js011',q:'What is the difference between null and undefined?',hint:'undefined: variable declared but not assigned, missing function return, missing object property. null: intentional absence of value, must be explicitly assigned. typeof null === "object" is a famous JS bug.',tags:['js','easy'],cat:'JavaScript'},
{id:'js012',q:'How does this work in JavaScript? What is binding?',hint:'this depends on call site. Global: window/undefined(strict). Method: the object. Arrow: lexical this from outer scope. call/apply/bind for explicit binding. Class methods lose this when destructured.',tags:['js','hard'],cat:'JavaScript'},

// ── TypeScript ────────────────────────────────
{id:'ts001',q:'What is the difference between any and unknown in TypeScript?',hint:'any disables type checking entirely. unknown requires type narrowing before use (typeof, instanceof, type guard). Always prefer unknown over any when the type is genuinely unknown.',tags:['ts','med'],cat:'TypeScript'},
{id:'ts002',q:'What are generics in TypeScript? Write a generic identity function.',hint:'Generics allow writing reusable code that works with multiple types. function identity<T>(arg: T): T { return arg; } Constraint: <T extends object>. Used in React: useState<User|null>(null).',tags:['ts','med'],cat:'TypeScript'},
{id:'ts003',q:'Explain the difference between interface and type in TypeScript.',hint:'interface: extendable with extends, declaration merging, best for object shapes. type: union/intersection types, mapped types, primitive aliases. Prefer interface for objects, type for complex types.',tags:['ts','med'],cat:'TypeScript'},
{id:'ts004',q:'What are utility types? Explain Partial, Pick, Omit, and Record.',hint:'Partial<T>: all props optional. Pick<T,K>: only keep keys K. Omit<T,K>: remove keys K. Record<K,V>: object with keys K and values V. ReturnType<F>, Parameters<F>, NonNullable<T>.',tags:['ts','med'],cat:'TypeScript'},
{id:'ts005',q:'What is a discriminated union? Give an example.',hint:'A union of types that share a common literal field used to narrow types. type State = {status:"loading"} | {status:"success",data:User} | {status:"error",message:string}. Switch on status to get full type safety.',tags:['ts','hard'],cat:'TypeScript'},
{id:'ts006',q:'What is strictNullChecks and why does it matter?',hint:'With strictNullChecks, null and undefined are not assignable to other types. Forces you to handle null cases explicitly. Eliminates entire class of runtime errors. Always enable in production.',tags:['ts','easy'],cat:'TypeScript'},
{id:'ts007',q:'What are mapped types? Write a DeepReadonly type.',hint:'Mapped types iterate over keys of a type: type Readonly<T> = { readonly [K in keyof T]: T[K] }. DeepReadonly adds recursion: type DeepReadonly<T> = { readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K] }',tags:['ts','hard'],cat:'TypeScript'},

// ── React ─────────────────────────────────────
{id:'r001',q:'When does a React component re-render?',hint:'1) State changes (useState/useReducer). 2) Props change. 3) Context value changes. 4) Parent re-renders (unless memo). 5) forceUpdate. React compares with Object.is() shallow equality.',tags:['react','med'],cat:'React'},
{id:'r002',q:'What is the difference between useEffect and useLayoutEffect?',hint:'useEffect runs after paint (async). useLayoutEffect runs synchronously after DOM mutations but before paint. Use useLayoutEffect only for DOM measurements to avoid visual flicker. 99% of cases: useEffect.',tags:['react','med'],cat:'React'},
{id:'r003',q:'Explain useMemo and useCallback. When do they actually help?',hint:'useMemo memoizes a value. useCallback memoizes a function reference. Only help when: (1) passed to React.memo children, (2) in dependency arrays of other hooks. Premature memoization is worse than none.',tags:['react','hard'],cat:'React'},
{id:'r004',q:'What is the React reconciliation algorithm?',hint:'React diffs virtual DOM trees top-down. Same type = update props. Different type = unmount/remount. Keys help identify list items across renders. O(n) algorithm with heuristics.',tags:['react','hard'],cat:'React'},
{id:'r005',q:'What is a stale closure in React hooks? How do you fix it?',hint:'A closure capturing an old state value inside useEffect or event handler. Fix: add the value to dependency array, or use functional setState update: setCount(c => c+1). useRef for values you need without triggering effects.',tags:['react','hard'],cat:'React'},
{id:'r006',q:'What is prop drilling and how do you solve it?',hint:'Passing props through many intermediate components that don\'t use them. Solutions: Context API (global/semi-global state), component composition (children prop), Zustand/Redux for complex global state.',tags:['react','easy'],cat:'React'},
{id:'r007',q:'Explain the useReducer hook. When would you prefer it over useState?',hint:'useReducer(reducer, initialState) returns [state, dispatch]. Prefer when: multiple related state fields, next state depends on previous, complex update logic, state transitions follow a pattern.',tags:['react','med'],cat:'React'},
{id:'r008',q:'What is React.memo? How does it work?',hint:'HOC that memoizes a component — skips re-render if props haven\'t changed (shallow comparison). Only works with React.memo + referentially stable props (useCallback for functions). Does NOT prevent renders from context changes.',tags:['react','med'],cat:'React'},
{id:'r009',q:'Explain code splitting in React with React.lazy and Suspense.',hint:'React.lazy(() => import("./Component")) loads component asynchronously. Wrap in <Suspense fallback={<Loading/>}>. Bundle split at route level is most impactful. Use with React Router\'s lazy loading.',tags:['react','med'],cat:'React'},
{id:'r010',q:'What are React Server Components? When would you use them?',hint:'Components that render on the server, have zero client JS bundle cost, can directly access databases/APIs. Cannot use hooks, event handlers, or browser APIs. Use for: data fetching, heavy computations, non-interactive UI.',tags:['react','hard'],cat:'React'},
{id:'r011',q:'How does React Context work internally? What are its performance implications?',hint:'All consumers re-render when context value changes, even if they only use a slice. Fix: split contexts by domain, useMemo on value, or use Zustand/Jotai for fine-grained subscriptions.',tags:['react','hard'],cat:'React'},
{id:'r012',q:'What is TanStack Query? How is it different from useEffect for data fetching?',hint:'Manages server state: caching, deduplication, background refetch, staleTime, gcTime, optimistic updates. useEffect has no caching, causes waterfalls, needs manual loading/error state. React Query eliminates 80% of data fetching code.',tags:['react','med'],cat:'React'},

// ── Next.js ───────────────────────────────────
{id:'nx001',q:'What is the difference between Server Components and Client Components in Next.js?',hint:'Server Components: render on server, zero client JS, can access DB directly, no hooks. Client Components: "use client", can use hooks/events/browser APIs, hydrated in browser. Default is Server Component in App Router.',tags:['react','med'],cat:'Next.js'},
{id:'nx002',q:'Explain Static Generation, SSR, and ISR in Next.js App Router.',hint:'Static: generated at build time, fastest, CDN cached. SSR: generated per request, always fresh data. ISR: static + revalidate after N seconds. In App Router: fetch cache options replace getStaticProps/getServerSideProps.',tags:['react','med'],cat:'Next.js'},
{id:'nx003',q:'What are Server Actions in Next.js?',hint:'Async functions that run on the server, called directly from client components. Replace API routes for mutations. Progressive enhancement: work without JS. Use with useFormState and useFormStatus for loading/error states.',tags:['react','hard'],cat:'Next.js'},

// ── CSS / Tailwind ────────────────────────────
{id:'css001',q:'Explain the CSS box model. What is box-sizing: border-box?',hint:'box-model: content + padding + border + margin. By default (content-box) width/height = content only. border-box includes padding+border in width/height — much more predictable. Reset with * { box-sizing: border-box }.',tags:['css','easy'],cat:'CSS'},
{id:'css002',q:'What is CSS specificity? How is it calculated?',hint:'Inline styles (1000) > ID (100) > class/attribute/pseudo-class (10) > element/pseudo-element (1). !important overrides all. Specificity fights are a sign of poor CSS architecture.',tags:['css','easy'],cat:'CSS'},
{id:'css003',q:'What is Flexbox? When use it vs CSS Grid?',hint:'Flexbox: one-dimensional (row or column), content-driven sizing. Grid: two-dimensional, layout-driven. Use Flex for nav bars, card content, centering. Use Grid for page layouts, gallery grids, overlapping elements.',tags:['css','easy'],cat:'CSS'},
{id:'css004',q:'Explain Tailwind\'s JIT mode and how it purges unused CSS.',hint:'JIT generates styles on-demand instead of pre-generating all combinations. PurgeCSS scans your source files for class names and removes unused ones. Result: tiny production CSS bundles.',tags:['css','med'],cat:'CSS'},

// ── DevOps ────────────────────────────────────
{id:'do001',q:'What is Docker? Explain images, containers, and layers.',hint:'Image: read-only template built from Dockerfile layers. Container: running instance of an image. Layers: each instruction creates a cached layer. docker build creates image, docker run creates container from image.',tags:['devops','easy'],cat:'DevOps'},
{id:'do002',q:'What is the difference between CMD and ENTRYPOINT in a Dockerfile?',hint:'ENTRYPOINT: always runs, defines the executable. CMD: default arguments to ENTRYPOINT or default command. docker run myimage --flag overrides CMD but not ENTRYPOINT. Best practice: ENTRYPOINT ["node"] CMD ["server.js"].',tags:['devops','med'],cat:'DevOps'},
{id:'do003',q:'Explain Kubernetes: what are Pods, Deployments, and Services?',hint:'Pod: smallest unit, one or more containers sharing network/storage. Deployment: manages replica set, handles rolling updates and rollbacks. Service: stable network endpoint for pods (ClusterIP, NodePort, LoadBalancer).',tags:['devops','med'],cat:'DevOps'},
{id:'do004',q:'What is CI/CD? Walk through a pipeline you have built.',hint:'CI: merge code frequently, run automated tests on each PR. CD: automatically deploy passing builds to staging or production. A good pipeline: lint → typecheck → unit tests → build → push image → deploy.',tags:['devops','med'],cat:'DevOps'},
{id:'do005',q:'What is Terraform? Explain state.',hint:'Infrastructure as Code tool. Terraform state tracks real-world resources vs config. State file is sensitive — store in S3+DynamoDB (locking) not Git. Plan shows diff, apply executes. Destroy removes all managed resources.',tags:['devops','med'],cat:'DevOps'},
{id:'do006',q:'What is a VPC? Explain public vs private subnets.',hint:'Virtual Private Cloud: isolated network in AWS. Public subnet: route table has internet gateway, resources get public IPs. Private subnet: no direct internet access, uses NAT gateway to reach internet. Put databases in private subnets always.',tags:['devops','med'],cat:'DevOps'},
{id:'do007',q:'What are the three pillars of observability?',hint:'Logs: timestamped records of events (Winston, CloudWatch Logs). Metrics: numerical measurements over time (CPU %, error rate). Traces: end-to-end request journey across services (Jaeger, X-Ray). All three together = full observability.',tags:['devops','med'],cat:'DevOps'},

// ── System Design ─────────────────────────────
{id:'sd001',q:'Design a URL shortener like bit.ly.',hint:'Requirements: short URL generation, redirect, analytics. DB: hash (base62, 6 chars = 56B combinations). Store: original URL, short code, click count, created date. Cache popular URLs in Redis. CDN for redirects. Handle collisions.',tags:['system','hard'],cat:'System Design'},
{id:'sd002',q:'How would you design a real-time notification system?',hint:'WebSockets or SSE for real-time push. Message queue (Kafka/SQS) for reliability. Fan-out service routes to connected users. Store unread notifications in DB. Redis for online user tracking. Exponential backoff for reconnection.',tags:['system','hard'],cat:'System Design'},
{id:'sd003',q:'What is the CAP theorem?',hint:'Distributed system can guarantee only 2 of 3: Consistency (all nodes see same data), Availability (requests always get a response), Partition tolerance (system works despite network splits). During partition: choose CP (bank) or AP (social feed).',tags:['system','hard'],cat:'System Design'},
{id:'sd004',q:'Explain REST vs GraphQL. When would you choose each?',hint:'REST: simple, cacheable, widely understood, multiple endpoints. GraphQL: single endpoint, client specifies exact data needed (no over/under-fetching), great for complex/nested data. REST for simple CRUD, GraphQL for mobile apps with bandwidth constraints.',tags:['system','med'],cat:'System Design'},
{id:'sd005',q:'What happens when you type a URL and press Enter?',hint:'DNS lookup → TCP handshake → TLS handshake → HTTP request → server processes → response → browser parses HTML → builds DOM → CSSOM → render tree → layout → paint → JS execution. CDN serves cached assets.',tags:['system','med'],cat:'System Design'},

// ── Behavioral ────────────────────────────────
{id:'bh001',q:'Tell me about yourself. (2 minutes)',hint:'Structure: [Brief background] → [What triggered the switch to tech] → [What you\'ve built in the last 80 days] → [What role you\'re targeting and why this company]. Practice until it sounds natural, not rehearsed.',tags:['behavioral','easy'],cat:'Behavioral'},
{id:'bh002',q:'Why are you switching careers at 33?',hint:'Frame as "moving toward" not "running from". Example: "I\'ve spent X years in [field] which gave me [skills]. I discovered programming [how] and realised I can solve bigger problems with code. I\'ve spent the last months building [projects] to make this switch properly."',tags:['behavioral','easy'],cat:'Behavioral'},
{id:'bh003',q:'Tell me about a challenge you faced and how you overcame it.',hint:'STAR: Situation → Task → Action → Result. Pick a real story. Focus on your specific actions, not team actions. Quantify the result if possible. Show what you learned.',tags:['behavioral','easy'],cat:'Behavioral'},
{id:'bh004',q:'Where do you see yourself in 2-3 years?',hint:'Show ambition but stay realistic. "I want to become a strong frontend developer who owns features end-to-end within the first year. In 2-3 years I aim to mentor juniors and contribute to technical decisions." Align with the company\'s growth.',tags:['behavioral','easy'],cat:'Behavioral'},
{id:'bh005',q:'What is your expected salary?',hint:'Research Hyderabad market: junior frontend ₹4-7 LPA, mid ₹7-14 LPA. Give a range, not a single number. Anchor high: "Based on my research and the skills I bring, I\'m targeting ₹X-Y LPA. I\'m open to discussing based on the full package."',tags:['behavioral','easy'],cat:'Behavioral'},
{id:'bh006',q:'Tell me about a time you had to learn something quickly.',hint:'This is your ace card — you just learned React, TypeScript, and DevOps in 80 days. Talk about a specific concept that was hard (closures, generics, etc.), how you broke it down, and built something to cement it.',tags:['behavioral','easy'],cat:'Behavioral'},

// ── Performance ───────────────────────────────
{id:'perf001',q:'How do you optimise the performance of a React application?',hint:'Code split at route level. Lazy load images. React.memo + useCallback for pure components. Virtualise long lists (TanStack Virtual). Avoid inline object/function props. Profile with React DevTools. Move state down.',tags:['react','hard'],cat:'Performance'},
{id:'perf002',q:'What is the difference between Lighthouse performance score metrics?',hint:'FCP: First Contentful Paint (time to first text/image). LCP: Largest Contentful Paint (main content loaded, target <2.5s). TBT: Total Blocking Time. CLS: Cumulative Layout Shift (visual stability). INP: Interaction to Next Paint.',tags:['css','med'],cat:'Performance'},
{id:'perf003',q:'What is lazy loading? How do you implement it for images?',hint:'Load resources only when needed. Images: loading="lazy" attribute (native). <IntersectionObserver> for custom logic. Blur-up technique for placeholders. Next/Image handles this automatically. Critical images should NOT be lazy loaded.',tags:['css','easy'],cat:'Performance'},

// ── Security ──────────────────────────────────
{id:'sec001',q:'What is XSS? How do you prevent it?',hint:'Cross-Site Scripting: attacker injects malicious script into pages. Prevention: never use innerHTML with user input, use textContent instead, CSP headers, sanitise with DOMPurify, HttpOnly cookies for session tokens.',tags:['js','med'],cat:'Security'},
{id:'sec002',q:'What is CORS? Why does it exist?',hint:'Cross-Origin Resource Sharing: browsers block cross-origin requests by default (same-origin policy). CORS headers tell browsers which origins are allowed. Server sets Access-Control-Allow-Origin. Preflight OPTIONS request for non-simple requests.',tags:['js','med'],cat:'Security'},
{id:'sec003',q:'JWT vs Sessions for authentication. Trade-offs?',hint:'JWT: stateless, scalable, self-contained, but cannot invalidate before expiry. Sessions: stateful, easy to invalidate, requires session store (Redis). Store JWTs in HttpOnly cookies (not localStorage) to prevent XSS. Use short expiry + refresh tokens.',tags:['js','med'],cat:'Security'},
];
