// ─── DATA ─────────────────────────────────────────────────────────────────────
const PHASES = [
{title:"Phase 1 — Foundations",days:"Days 1–10",icon:"⬡",color:"#00d9a0",dim:"rgba(0,217,160,.1)",data:[
  {day:"Day 1",label:"How the web works",tasks:[
    {t:"Concept: How browsers render HTML/CSS/JS — request → response → DOM → paint",k:"concept"},
    {t:"Concept: HTTP vs HTTPS, status codes (200, 404, 500), REST basics",k:"concept"},
    {t:"Concept: DNS, CDN, hosting — what happens when you type a URL",k:"concept"},
    {t:"Code: Set up VS Code, install Live Server extension, create first HTML file",k:"code"},
    {t:"Quiz: What is the DOM? What does HTTP 404 mean? Explain GET vs POST",k:"quiz"},
  ]},
  {day:"Day 2",label:"HTML5 deep dive",tasks:[
    {t:"Concept: Semantic HTML — header, main, section, article, nav, footer",k:"concept"},
    {t:"Concept: Forms — input types, labels, required, form validation attributes",k:"concept"},
    {t:"Concept: Accessibility basics — alt text, ARIA roles, tab order",k:"concept"},
    {t:"Code: Build a fully semantic personal bio page with a contact form",k:"code"},
    {t:"Quiz: Why use semantic tags over divs? What is ARIA?",k:"quiz"},
  ]},
  {day:"Day 3",label:"CSS fundamentals",tasks:[
    {t:"Concept: Box model — margin, border, padding, content. display block/inline/inline-block",k:"concept"},
    {t:"Concept: Selectors — class, id, pseudo-class (:hover, :focus), specificity",k:"concept"},
    {t:"Concept: Positioning — static, relative, absolute, fixed, sticky",k:"concept"},
    {t:"Code: Style your Day 2 bio page with a card layout and a sticky nav",k:"code"},
    {t:"Quiz: Explain specificity. When would you use position:absolute vs fixed?",k:"quiz"},
  ]},
  {day:"Day 4",label:"CSS Flexbox",tasks:[
    {t:"Concept: Flexbox — flex-direction, justify-content, align-items, flex-wrap, gap",k:"concept"},
    {t:"Concept: flex-grow, flex-shrink, flex-basis — how children resize",k:"concept"},
    {t:"Code: Build a responsive navbar and a 3-column card grid using only flexbox",k:"code"},
    {t:"Code: Recreate the classic holy grail layout (header, sidebars, main, footer)",k:"code"},
    {t:"Quiz: Difference between justify-content and align-items? What does flex:1 mean?",k:"quiz"},
  ]},
  {day:"Day 5",label:"CSS Grid + Responsive",tasks:[
    {t:"Concept: CSS Grid — grid-template-columns, grid-area, auto-fit, minmax",k:"concept"},
    {t:"Concept: Media queries — mobile first, breakpoints, min-width vs max-width",k:"concept"},
    {t:"Concept: CSS custom properties (variables) — :root, var(--name)",k:"concept"},
    {t:"Code: Build a Pinterest-style masonry photo grid that collapses to 1 column on mobile",k:"code"},
    {t:"Quiz: When to use Grid vs Flexbox? What is mobile-first design?",k:"quiz"},
  ]},
  {day:"Day 6",label:"JavaScript fundamentals I",tasks:[
    {t:"Concept: Variables — var/let/const, scope (block vs function), hoisting",k:"concept"},
    {t:"Concept: Data types — string, number, boolean, null, undefined, object, array",k:"concept"},
    {t:"Concept: Functions — declaration vs expression vs arrow functions, return values",k:"concept"},
    {t:"Concept: Arrays — map, filter, reduce, find, forEach, spread operator",k:"concept"},
    {t:"Code: Write 15 array manipulation exercises (sort names, filter even numbers, etc.)",k:"code"},
    {t:"Quiz: Explain hoisting. Difference between null and undefined?",k:"quiz"},
  ]},
  {day:"Day 7",label:"JavaScript fundamentals II",tasks:[
    {t:"Concept: Objects — dot notation, destructuring, spread, Object.keys/values/entries",k:"concept"},
    {t:"Concept: Callbacks, Promises, async/await — the event loop explained",k:"concept"},
    {t:"Concept: Fetch API — GET and POST requests, handling JSON responses",k:"concept"},
    {t:"Code: Fetch data from JSONPlaceholder API and render it in a styled table",k:"code"},
    {t:"Quiz: What is the event loop? Rewrite a Promise chain using async/await",k:"quiz"},
  ]},
  {day:"Day 8",label:"DOM manipulation + Events",tasks:[
    {t:"Concept: querySelector, getElementById, createElement, appendChild, innerHTML vs textContent",k:"concept"},
    {t:"Concept: Event listeners — click, input, submit, keydown. Event bubbling and delegation",k:"concept"},
    {t:"Concept: localStorage — getItem, setItem, JSON.stringify/parse",k:"concept"},
    {t:"Code: Build a fully functional Todo app (add, delete, toggle done) with localStorage",k:"project"},
    {t:"Quiz: What is event delegation? Why avoid innerHTML for user input?",k:"quiz"},
  ]},
  {day:"Day 9",label:"Git and GitHub",tasks:[
    {t:"Concept: Git init, add, commit, status, log, diff — the local workflow",k:"concept"},
    {t:"Concept: Branching — checkout, merge, rebase, resolving conflicts",k:"concept"},
    {t:"Concept: GitHub — push, pull, clone, fork, pull requests, .gitignore",k:"concept"},
    {t:"Code: Push your Todo app to GitHub with a descriptive README",k:"code"},
    {t:"Quiz: What is a merge conflict? When would you rebase instead of merge?",k:"quiz"},
  ]},
  {day:"Day 10",label:"Review + Mini project",tasks:[
    {t:"Review: Revisit any Day 1-9 concept you felt shaky on",k:"concept"},
    {t:"Project: Build a Weather Dashboard — fetch OpenWeatherMap API, 5-day forecast, localStorage",k:"project"},
    {t:"Quiz: Explain async/await, event delegation, and the box model out loud",k:"quiz"},
    {t:"Code: Push Weather Dashboard to GitHub with README screenshots",k:"code"},
  ]},
]},
{title:"Phase 2 — TypeScript",days:"Days 11–25",icon:"T",color:"#4fa8ff",dim:"rgba(79,168,255,.1)",data:[
  {day:"Day 11",label:"Why TypeScript exists",tasks:[
    {t:"Concept: Static vs dynamic typing — why TypeScript catches bugs JavaScript cannot",k:"concept"},
    {t:"Concept: Install TypeScript globally, tsconfig.json basics — target, strict, outDir",k:"concept"},
    {t:"Code: Convert your Day 8 Todo app from JS to TS — fix every type error",k:"code"},
    {t:"Quiz: What is a type annotation? What does strict mode enforce?",k:"quiz"},
  ]},
  {day:"Day 12",label:"Primitive types + type inference",tasks:[
    {t:"Concept: string, number, boolean, null, undefined, void, never, any, unknown",k:"concept"},
    {t:"Concept: Type inference — when TS figures out types automatically vs when you must annotate",k:"concept"},
    {t:"Concept: Union types (string | number), literal types",k:"concept"},
    {t:"Code: Write 20 typed functions covering all primitive types",k:"code"},
    {t:"Quiz: Difference between any and unknown? When would you use never?",k:"quiz"},
  ]},
  {day:"Day 13",label:"Interfaces and Type aliases",tasks:[
    {t:"Concept: interface — defining object shapes, optional properties, readonly",k:"concept"},
    {t:"Concept: type alias — when to use type vs interface",k:"concept"},
    {t:"Concept: Extending interfaces, intersection types",k:"concept"},
    {t:"Code: Model a User, Product, and Order system with interfaces and CRUD functions",k:"code"},
    {t:"Quiz: interface vs type — what can interface do that type cannot?",k:"quiz"},
  ]},
  {day:"Day 14",label:"Arrays, Tuples, Enums",tasks:[
    {t:"Concept: Typed arrays — string[], Array with number",k:"concept"},
    {t:"Concept: Tuples — fixed-length arrays with specific types at each position",k:"concept"},
    {t:"Concept: Enums — const enum vs regular enum, string enums",k:"concept"},
    {t:"Code: Build a typed shopping cart with Product array, CartItem tuples, and OrderStatus enum",k:"code"},
    {t:"Quiz: When to use a tuple over an array? Why prefer const enum?",k:"quiz"},
  ]},
  {day:"Day 15",label:"Functions in TypeScript",tasks:[
    {t:"Concept: Function type signatures, optional and default parameters",k:"concept"},
    {t:"Concept: Overloading — multiple function signatures for different argument types",k:"concept"},
    {t:"Concept: Type guards — typeof, instanceof, custom type predicates (is keyword)",k:"concept"},
    {t:"Code: Write a data-processing utility library with 10 fully typed functions",k:"code"},
    {t:"Quiz: What is a type guard? Implement a typed filter function",k:"quiz"},
  ]},
  {day:"Day 16",label:"Generics I",tasks:[
    {t:"Concept: Generic functions — T syntax, why generics exist",k:"concept"},
    {t:"Concept: Generic interfaces and type aliases",k:"concept"},
    {t:"Concept: Constraints — extends keyword, keyof constraint",k:"concept"},
    {t:"Code: Build a generic Stack and Queue data structure",k:"code"},
    {t:"Quiz: Rewrite Array.prototype.map with full TypeScript generics",k:"quiz"},
  ]},
  {day:"Day 17",label:"Generics II + Utility types",tasks:[
    {t:"Concept: Partial, Required, Readonly, Pick, Omit utility types",k:"concept"},
    {t:"Concept: Record, ReturnType, Parameters, NonNullable utility types",k:"concept"},
    {t:"Code: Build a typed API response handler using Partial, Omit, and Record",k:"code"},
    {t:"Quiz: What does Omit produce? When use Partial?",k:"quiz"},
  ]},
  {day:"Day 18",label:"Classes in TypeScript",tasks:[
    {t:"Concept: class syntax — constructor, properties, methods, access modifiers",k:"concept"},
    {t:"Concept: abstract classes vs interfaces, implements vs extends",k:"concept"},
    {t:"Concept: Parameter properties shorthand in constructors",k:"concept"},
    {t:"Code: Model a bank account system with Account (abstract), SavingsAccount, CurrentAccount",k:"code"},
    {t:"Quiz: When use abstract class over interface? What is parameter property shorthand?",k:"quiz"},
  ]},
  {day:"Day 19",label:"Modules + Declaration files",tasks:[
    {t:"Concept: ES modules in TS — import/export, default vs named",k:"concept"},
    {t:"Concept: Declaration files (.d.ts) — what they are, @types packages, DefinitelyTyped",k:"concept"},
    {t:"Concept: Path aliases in tsconfig — @/components, @/utils",k:"concept"},
    {t:"Code: Refactor your Weather Dashboard into typed modules with barrel exports",k:"code"},
    {t:"Quiz: What is a .d.ts file? How do you install types for a JS library?",k:"quiz"},
  ]},
  {day:"Day 20",label:"Advanced types I",tasks:[
    {t:"Concept: Mapped types — iterating over keyof T",k:"concept"},
    {t:"Concept: Conditional types — T extends U ? X : Y",k:"concept"},
    {t:"Concept: Template literal types",k:"concept"},
    {t:"Code: Write a DeepReadonly and a Nullable mapped type from scratch",k:"code"},
    {t:"Quiz: Explain how conditional types work. Write an IsArray type",k:"quiz"},
  ]},
  {day:"Day 21",label:"Advanced types II",tasks:[
    {t:"Concept: Discriminated unions — type-safe state machines",k:"concept"},
    {t:"Concept: Exhaustive checks with never in switch statements",k:"concept"},
    {t:"Concept: Infer keyword in conditional types",k:"concept"},
    {t:"Code: Model a UI loading state (Idle, Loading, Success, Error) with discriminated union",k:"code"},
    {t:"Quiz: How does exhaustive checking work? Write a ReturnType clone using infer",k:"quiz"},
  ]},
  {day:"Day 22",label:"TypeScript + Node.js",tasks:[
    {t:"Concept: Set up a TS Node.js project — ts-node, nodemon, tsconfig for Node",k:"concept"},
    {t:"Concept: Typing Express.js routes — Request, Response, NextFunction generics",k:"concept"},
    {t:"Code: Build a typed REST API with 5 routes — GET list, GET by id, POST, PUT, DELETE",k:"code"},
    {t:"Quiz: How do you type query params and body in Express? What is ts-node?",k:"quiz"},
  ]},
  {day:"Day 23",label:"Error handling + Strict mode",tasks:[
    {t:"Concept: strictNullChecks — why it matters, the non-null assertion operator",k:"concept"},
    {t:"Concept: Error handling patterns — Result type, typed custom errors",k:"concept"},
    {t:"Concept: noImplicitAny, strictFunctionTypes, strictPropertyInitialization",k:"concept"},
    {t:"Code: Refactor your Day 22 API to use a Result pattern",k:"code"},
    {t:"Quiz: What is strictNullChecks? When is using ! acceptable?",k:"quiz"},
  ]},
  {day:"Day 24",label:"TypeScript tooling",tasks:[
    {t:"Concept: ESLint with @typescript-eslint — setup, key rules",k:"concept"},
    {t:"Concept: Prettier — auto-formatting, .prettierrc config",k:"concept"},
    {t:"Concept: Vitest / Jest basics — writing typed unit tests",k:"concept"},
    {t:"Code: Add ESLint + Prettier + 10 unit tests to your Day 22 API",k:"code"},
    {t:"Quiz: What does ESLint enforce? Why write tests for your API?",k:"quiz"},
  ]},
  {day:"Day 25",label:"TypeScript review + challenge",tasks:[
    {t:"Review: Generics, utility types, discriminated unions — explain each to yourself",k:"concept"},
    {t:"Project: Build a typed CLI task manager (add, list, complete, delete) stored in JSON",k:"project"},
    {t:"Quiz: Given a JS snippet, annotate it fully in TypeScript from memory",k:"quiz"},
    {t:"Code: Push to GitHub, write a README explaining the TypeScript patterns used",k:"code"},
  ]},
]},
{title:"Phase 3 — React + Tailwind",days:"Days 26–45",icon:"⚛",color:"#ff7eb3",dim:"rgba(255,126,179,.1)",data:[
  {day:"Day 26",label:"React fundamentals",tasks:[
    {t:"Concept: What is React? Virtual DOM, reconciliation, why components",k:"concept"},
    {t:"Concept: Vite setup — create a React+TS project, folder structure",k:"concept"},
    {t:"Concept: JSX — what it compiles to, expressions, self-closing tags",k:"concept"},
    {t:"Code: Build 5 functional components — Button, Card, Badge, Avatar, Alert",k:"code"},
    {t:"Quiz: What is the virtual DOM? Why does React use keys in lists?",k:"quiz"},
  ]},
  {day:"Day 27",label:"Props + Component patterns",tasks:[
    {t:"Concept: Props — passing data down, typing props with TypeScript interfaces",k:"concept"},
    {t:"Concept: children prop — React.ReactNode, composition pattern",k:"concept"},
    {t:"Concept: Default props, optional props, prop drilling problem",k:"concept"},
    {t:"Code: Build a ProductCard component used in a ProductGrid with typed props",k:"code"},
    {t:"Quiz: What is prop drilling? When does it become a problem?",k:"quiz"},
  ]},
  {day:"Day 28",label:"useState hook",tasks:[
    {t:"Concept: useState — state vs props, re-renders, functional updates",k:"concept"},
    {t:"Concept: State batching, stale closure problem",k:"concept"},
    {t:"Concept: Typing useState with generics",k:"concept"},
    {t:"Code: Build a multi-step signup form with full state management",k:"code"},
    {t:"Quiz: What is a stale closure in React? How do functional updates fix it?",k:"quiz"},
  ]},
  {day:"Day 29",label:"useEffect hook",tasks:[
    {t:"Concept: useEffect — dependency array, cleanup functions, when it runs",k:"concept"},
    {t:"Concept: Common mistakes — missing deps, infinite loops, memory leaks",k:"concept"},
    {t:"Concept: Data fetching with useEffect, loading and error states",k:"concept"},
    {t:"Code: Fetch and display paginated GitHub repos for a username typed in an input",k:"code"},
    {t:"Quiz: When does useEffect with [] run vs [value]? What is a cleanup function?",k:"quiz"},
  ]},
  {day:"Day 30",label:"Tailwind CSS I",tasks:[
    {t:"Concept: Utility-first philosophy — why Tailwind beats custom CSS at scale",k:"concept"},
    {t:"Concept: Core utilities — spacing, sizing, flex, grid, colors",k:"concept"},
    {t:"Concept: Responsive prefixes — sm: md: lg: xl: 2xl:",k:"concept"},
    {t:"Concept: State variants — hover: focus: active: disabled:",k:"concept"},
    {t:"Code: Rebuild your Day 27 ProductCard and Grid in Tailwind (no CSS file)",k:"code"},
    {t:"Quiz: How does Tailwind purge unused classes? What is JIT mode?",k:"quiz"},
  ]},
  {day:"Day 31",label:"Tailwind CSS II",tasks:[
    {t:"Concept: Dark mode — dark: variant, class strategy",k:"concept"},
    {t:"Concept: Custom config — extend colors, fonts, spacing in tailwind.config.js",k:"concept"},
    {t:"Concept: @apply directive — when and why (sparingly)",k:"concept"},
    {t:"Concept: cn() utility with clsx + tailwind-merge — conditional classes",k:"concept"},
    {t:"Code: Add dark mode toggle and a custom color theme to your app",k:"code"},
    {t:"Quiz: Why is tailwind-merge needed? When would you use @apply?",k:"quiz"},
  ]},
  {day:"Day 32",label:"useReducer + useContext",tasks:[
    {t:"Concept: useReducer — actions, reducer function, dispatch, when to prefer over useState",k:"concept"},
    {t:"Concept: useContext — Context.Provider, createContext, avoiding prop drilling",k:"concept"},
    {t:"Concept: Combining useReducer + useContext for global state",k:"concept"},
    {t:"Code: Build a shopping cart with useReducer + Context (add, remove, quantity, total)",k:"code"},
    {t:"Quiz: When useReducer vs useState? What causes Context re-render issues?",k:"quiz"},
  ]},
  {day:"Day 33",label:"Custom hooks",tasks:[
    {t:"Concept: What makes a custom hook — starts with use, can call other hooks",k:"concept"},
    {t:"Concept: Why extract logic into custom hooks — reusability and testing",k:"concept"},
    {t:"Code: Build useFetch, useLocalStorage, useDebounce, useToggle, useWindowSize",k:"code"},
    {t:"Quiz: Explain useFetch — what does it return? How would you test a custom hook?",k:"quiz"},
  ]},
  {day:"Day 34",label:"React Router v6",tasks:[
    {t:"Concept: BrowserRouter, Routes, Route, Link, NavLink — SPA routing",k:"concept"},
    {t:"Concept: URL params (:id), useParams, useNavigate, useLocation",k:"concept"},
    {t:"Concept: Nested routes, Outlet, layout routes",k:"concept"},
    {t:"Concept: Protected routes — redirect if not authenticated",k:"concept"},
    {t:"Code: Add multi-page routing to your shopping cart app",k:"code"},
    {t:"Quiz: Difference between Link and useNavigate? What is Outlet?",k:"quiz"},
  ]},
  {day:"Day 35",label:"Forms — React Hook Form + Zod",tasks:[
    {t:"Concept: React Hook Form — register, handleSubmit, formState, Controller",k:"concept"},
    {t:"Concept: Zod — schema validation, z.object, z.string, email, refine",k:"concept"},
    {t:"Concept: zodResolver — connecting Zod schema to RHF",k:"concept"},
    {t:"Code: Build a full registration form with 8 fields, Zod validation, and error messages",k:"code"},
    {t:"Quiz: Why React Hook Form over controlled inputs? What does zodResolver do?",k:"quiz"},
  ]},
  {day:"Day 36",label:"Data fetching — TanStack Query",tasks:[
    {t:"Concept: TanStack Query — useQuery, useMutation, QueryClient",k:"concept"},
    {t:"Concept: Caching, staleTime, gcTime, refetchOnWindowFocus",k:"concept"},
    {t:"Concept: Optimistic updates, invalidateQueries, pagination with useInfiniteQuery",k:"concept"},
    {t:"Code: Replace all useEffect fetch calls in your app with React Query",k:"code"},
    {t:"Quiz: What is staleTime? How does React Query eliminate loading flickers?",k:"quiz"},
  ]},
  {day:"Day 37",label:"State management — Zustand",tasks:[
    {t:"Concept: Zustand — create store, selectors, actions, middleware",k:"concept"},
    {t:"Concept: When Zustand vs React Query vs Context — the decision matrix",k:"concept"},
    {t:"Concept: persist middleware — localStorage integration",k:"concept"},
    {t:"Code: Migrate your shopping cart Context to a Zustand store",k:"code"},
    {t:"Quiz: Zustand vs Redux — key differences? When NOT to use global state?",k:"quiz"},
  ]},
  {day:"Day 38",label:"Performance optimization",tasks:[
    {t:"Concept: useMemo, useCallback — what they memoize and when they help",k:"concept"},
    {t:"Concept: React.memo — preventing unnecessary re-renders",k:"concept"},
    {t:"Concept: Code splitting — React.lazy, Suspense, dynamic import",k:"concept"},
    {t:"Concept: React DevTools Profiler — identifying expensive renders",k:"concept"},
    {t:"Code: Profile your app, find 3 performance issues, fix them",k:"code"},
    {t:"Quiz: When does useMemo NOT help? What is the cost of React.memo?",k:"quiz"},
  ]},
  {day:"Day 39",label:"Testing React",tasks:[
    {t:"Concept: Vitest + React Testing Library setup, render, screen, userEvent",k:"concept"},
    {t:"Concept: Queries — getByRole, getByText, getByLabelText, findBy (async)",k:"concept"},
    {t:"Concept: Mocking — vi.mock, MSW (Mock Service Worker) for API mocking",k:"concept"},
    {t:"Code: Write 15 tests covering your shopping cart — add item, remove item, quantity update",k:"code"},
    {t:"Quiz: Why prefer getByRole over getByTestId? What is MSW?",k:"quiz"},
  ]},
  {day:"Day 40",label:"Component library patterns",tasks:[
    {t:"Concept: shadcn/ui — what it is, how it differs from MUI (you own the code)",k:"concept"},
    {t:"Concept: Radix UI primitives — accessible, headless components",k:"concept"},
    {t:"Concept: Compound component pattern, Render prop pattern",k:"concept"},
    {t:"Code: Install shadcn/ui, use Dialog, Dropdown, Toast, DataTable in your app",k:"code"},
    {t:"Quiz: shadcn/ui vs MUI — trade-offs? What is a headless component?",k:"quiz"},
  ]},
  {day:"Day 41",label:"Next.js fundamentals",tasks:[
    {t:"Concept: Next.js App Router — file-based routing, layout.tsx, page.tsx, loading.tsx",k:"concept"},
    {t:"Concept: Server Components vs Client Components — use client directive",k:"concept"},
    {t:"Concept: Server Actions — form handling without API routes",k:"concept"},
    {t:"Code: Migrate your React app to Next.js, convert data fetching to server components",k:"code"},
    {t:"Quiz: When use client? What is a Server Action?",k:"quiz"},
  ]},
  {day:"Day 42",label:"Next.js advanced",tasks:[
    {t:"Concept: Static generation vs Server-side rendering vs ISR in App Router",k:"concept"},
    {t:"Concept: Next.js Image, Font optimization, Metadata API",k:"concept"},
    {t:"Concept: API routes (route.ts) — building a Next.js backend",k:"concept"},
    {t:"Code: Add SSR product pages and a metadata setup to your Next.js app",k:"code"},
    {t:"Quiz: Difference between generateStaticParams and SSR? What is ISR?",k:"quiz"},
  ]},
  {day:"Day 43",label:"Authentication",tasks:[
    {t:"Concept: JWT — header.payload.signature, access vs refresh tokens",k:"concept"},
    {t:"Concept: NextAuth.js (Auth.js) — providers, session, callbacks",k:"concept"},
    {t:"Concept: Protecting routes in Next.js with middleware",k:"concept"},
    {t:"Code: Add Google OAuth login to your Next.js app with protected dashboard route",k:"code"},
    {t:"Quiz: What is a refresh token? Why store JWT in httpOnly cookie?",k:"quiz"},
  ]},
  {day:"Day 44",label:"Databases + Prisma",tasks:[
    {t:"Concept: PostgreSQL basics — tables, columns, relations, SQL SELECT/INSERT/UPDATE/DELETE",k:"concept"},
    {t:"Concept: Prisma ORM — schema.prisma, models, migrations, Prisma Client",k:"concept"},
    {t:"Concept: Relations — one-to-many, many-to-many in Prisma",k:"concept"},
    {t:"Code: Add a PostgreSQL database to your Next.js app, store users and products via Prisma",k:"code"},
    {t:"Quiz: What is an ORM? Write a Prisma query to find all products under 500 rupees",k:"quiz"},
  ]},
  {day:"Day 45",label:"Phase 3 review + full-stack project",tasks:[
    {t:"Review: React hooks, Tailwind, Next.js App Router, Prisma — gaps?",k:"concept"},
    {t:"Project: Full-stack e-commerce store — SSR listing, Zustand cart, RHF+Zod checkout, NextAuth, Prisma orders",k:"project"},
    {t:"Code: Deploy to Vercel, connect Supabase/Neon PostgreSQL",k:"code"},
    {t:"Quiz: Explain your app architecture — what renders on server vs client?",k:"quiz"},
  ]},
]},
{title:"Phase 4 — DevOps + Cloud",days:"Days 46–55",icon:"☁",color:"#ff8c42",dim:"rgba(255,140,66,.1)",data:[
  {day:"Day 46",label:"Linux + command line",tasks:[
    {t:"Concept: File system — ls, cd, mkdir, rm, cp, mv, find, grep, cat, tail, chmod",k:"concept"},
    {t:"Concept: Processes — ps, kill, top/htop, background jobs and nohup",k:"concept"},
    {t:"Concept: SSH — key pair generation, ssh-copy-id, connecting to a remote server",k:"concept"},
    {t:"Code: Set up a free-tier EC2 Linux server, deploy a Node.js app manually",k:"code"},
    {t:"Quiz: How do file permissions (chmod 755) work? What does nohup do?",k:"quiz"},
  ]},
  {day:"Day 47",label:"Docker I — containers",tasks:[
    {t:"Concept: What is Docker — containers vs VMs, images vs containers",k:"concept"},
    {t:"Concept: Dockerfile — FROM, WORKDIR, COPY, RUN, CMD, EXPOSE",k:"concept"},
    {t:"Concept: docker build, docker run, docker ps, docker logs, docker exec",k:"concept"},
    {t:"Code: Write a Dockerfile for your Next.js app, build and run it locally",k:"code"},
    {t:"Quiz: Container vs VM — key difference? What is a Docker layer?",k:"quiz"},
  ]},
  {day:"Day 48",label:"Docker II — compose + registry",tasks:[
    {t:"Concept: docker-compose — services, volumes, networks, depends_on",k:"concept"},
    {t:"Concept: Environment variables in Docker — .env, ARG vs ENV",k:"concept"},
    {t:"Concept: Docker Hub and GitHub Container Registry — push and pull images",k:"concept"},
    {t:"Code: Write docker-compose.yml for your Next.js app + PostgreSQL + pgAdmin",k:"code"},
    {t:"Quiz: What is a Docker volume? Why not store DB data in a container?",k:"quiz"},
  ]},
  {day:"Day 49",label:"CI/CD with GitHub Actions",tasks:[
    {t:"Concept: What is CI/CD — continuous integration, continuous delivery/deployment",k:"concept"},
    {t:"Concept: GitHub Actions — workflow YAML, on: triggers, jobs, steps, runners",k:"concept"},
    {t:"Concept: Secrets in GitHub Actions — storing API keys safely",k:"concept"},
    {t:"Code: CI pipeline — on PR: lint + typecheck + test. On merge: build Docker image + push to registry",k:"code"},
    {t:"Quiz: Difference between CI and CD? What is a GitHub Actions runner?",k:"quiz"},
  ]},
  {day:"Day 50",label:"AWS fundamentals",tasks:[
    {t:"Concept: AWS account setup, IAM — users, roles, policies, principle of least privilege",k:"concept"},
    {t:"Concept: S3 — buckets, objects, public access, static website hosting",k:"concept"},
    {t:"Concept: EC2 — instance types, key pairs, security groups, elastic IP",k:"concept"},
    {t:"Code: Host your Next.js static export on S3 + CloudFront CDN",k:"code"},
    {t:"Quiz: What is IAM? Why never use your AWS root account day-to-day?",k:"quiz"},
  ]},
  {day:"Day 51",label:"AWS — compute + networking",tasks:[
    {t:"Concept: VPC — subnets (public/private), route tables, internet gateway, NAT gateway",k:"concept"},
    {t:"Concept: RDS — managed PostgreSQL, free tier, parameter groups, connection strings",k:"concept"},
    {t:"Concept: Elastic Beanstalk and ECS basics — deploying containerized apps",k:"concept"},
    {t:"Code: Deploy your Next.js Docker container to EC2, connect to RDS PostgreSQL",k:"code"},
    {t:"Quiz: Public subnet vs private subnet — when use each? What is a NAT gateway?",k:"quiz"},
  ]},
  {day:"Day 52",label:"Infrastructure as Code — Terraform",tasks:[
    {t:"Concept: IaC concept — why define infrastructure in code",k:"concept"},
    {t:"Concept: Terraform — provider, resource, variable, output, state file",k:"concept"},
    {t:"Concept: terraform init, plan, apply, destroy workflow",k:"concept"},
    {t:"Code: Write Terraform to provision an S3 bucket + EC2 instance on AWS",k:"code"},
    {t:"Quiz: What is terraform state? Why is the state file sensitive?",k:"quiz"},
  ]},
  {day:"Day 53",label:"Kubernetes basics",tasks:[
    {t:"Concept: K8s architecture — cluster, node, pod, deployment, service, ingress",k:"concept"},
    {t:"Concept: kubectl commands — get, describe, apply, delete, logs, exec",k:"concept"},
    {t:"Concept: YAML manifests — Deployment and Service definition",k:"concept"},
    {t:"Code: Run your Docker app on a local minikube cluster with a Deployment + Service",k:"code"},
    {t:"Quiz: Pod vs Deployment vs Service — what does each do?",k:"quiz"},
  ]},
  {day:"Day 54",label:"Monitoring + Logging",tasks:[
    {t:"Concept: Observability — logs, metrics, traces (the three pillars)",k:"concept"},
    {t:"Concept: AWS CloudWatch — log groups, alarms, metrics dashboard",k:"concept"},
    {t:"Concept: Error tracking — Sentry setup in a Next.js app",k:"concept"},
    {t:"Code: Add Sentry to your Next.js app, create a CloudWatch alarm for CPU above 80%",k:"code"},
    {t:"Quiz: Difference between logging and monitoring? What is a trace?",k:"quiz"},
  ]},
  {day:"Day 55",label:"DevOps review + pipeline project",tasks:[
    {t:"Review: Docker, GitHub Actions, AWS, Terraform, K8s basics — gaps?",k:"concept"},
    {t:"Project: Full CI/CD pipeline — push triggers tests, builds Docker image, pushes to ECR, deploys to EC2",k:"project"},
    {t:"Quiz: Walk through your pipeline end-to-end out loud",k:"quiz"},
    {t:"Code: Document the pipeline architecture in your GitHub README with a diagram",k:"code"},
  ]},
]},
{title:"Phase 5 — Portfolio Projects",days:"Days 56–65",icon:"◈",color:"#b98aff",dim:"rgba(185,138,255,.1)",data:[
  {day:"Days 56-58",label:"Project 1 — SaaS dashboard",tasks:[
    {t:"Project: Build a SaaS analytics dashboard — Next.js, Tailwind, Recharts, auth, Prisma + PostgreSQL",k:"project"},
    {t:"Code: Features — user login, data overview cards, line/bar charts, date range filter, export CSV",k:"code"},
    {t:"Code: Deploy to Vercel + Supabase, write README with screenshots and tech stack",k:"code"},
  ]},
  {day:"Days 59-61",label:"Project 2 — Real-time app",tasks:[
    {t:"Project: Build a real-time chat app — Next.js, Pusher or Socket.io, Zustand, Prisma",k:"project"},
    {t:"Code: Features — rooms, online users, typing indicator, message history, auth",k:"code"},
    {t:"Code: Deploy with Docker on EC2, set up CI/CD pipeline",k:"code"},
  ]},
  {day:"Days 62-63",label:"Portfolio site",tasks:[
    {t:"Project: Build your personal portfolio — Next.js, Tailwind, Framer Motion animations",k:"project"},
    {t:"Code: Sections — hero, about, tech stack, projects (with live links + GitHub), contact form",k:"code"},
    {t:"Code: Perfect Lighthouse score (100 performance, 100 accessibility, 100 SEO)",k:"code"},
  ]},
  {day:"Days 64-65",label:"Polish + LinkedIn",tasks:[
    {t:"Code: Fix any bugs, improve mobile responsiveness across all 3 projects",k:"code"},
    {t:"Project: Write detailed case study READMEs — problem, solution, tech choices, challenges",k:"project"},
    {t:"Quiz: Can you explain every line of code in each project? Expect this in interviews",k:"quiz"},
    {t:"Code: Set up LinkedIn — headline Frontend Developer React TypeScript Next.js, feature all 3 projects",k:"code"},
  ]},
]},
{title:"Phase 6 — Interview Prep",days:"Days 66–80",icon:"◉",color:"#ffc850",dim:"rgba(255,200,80,.1)",data:[
  {day:"Days 66-67",label:"JavaScript and TS interview questions",tasks:[
    {t:"Quiz: Explain closures, prototypal inheritance, event loop, microtasks vs macrotasks",k:"quiz"},
    {t:"Quiz: What is debounce vs throttle? Implement both from scratch",k:"quiz"},
    {t:"Quiz: Explain TypeScript generics, utility types, and discriminated unions",k:"quiz"},
    {t:"Code: LeetCode easy-medium: Two Sum, Valid Parentheses, Reverse Linked List",k:"code"},
  ]},
  {day:"Days 68-69",label:"React interview questions",tasks:[
    {t:"Quiz: Explain the React rendering cycle — when does a component re-render?",k:"quiz"},
    {t:"Quiz: useEffect vs useLayoutEffect, useMemo vs useCallback — real differences",k:"quiz"},
    {t:"Quiz: How does React Query caching work? Explain staleTime vs gcTime",k:"quiz"},
    {t:"Code: Live coding: build a debounced search input with loading state in 20 min",k:"code"},
  ]},
  {day:"Days 70-71",label:"System design basics",tasks:[
    {t:"Concept: How to approach a system design question — requirements, scale, components",k:"concept"},
    {t:"Quiz: Design a URL shortener — components, database schema, scaling",k:"quiz"},
    {t:"Quiz: Design a Twitter feed — how to handle 1M users, caching strategy",k:"quiz"},
    {t:"Quiz: REST vs GraphQL — when to use which?",k:"quiz"},
  ]},
  {day:"Days 72-73",label:"DevOps interview questions",tasks:[
    {t:"Quiz: Explain Docker — images, containers, layers, volumes, networking",k:"quiz"},
    {t:"Quiz: What is Kubernetes? Explain pod, deployment, service, ingress",k:"quiz"},
    {t:"Quiz: Walk through a CI/CD pipeline you have built",k:"quiz"},
    {t:"Quiz: What happens when you type a URL — DNS, CDN, TLS, server rendering",k:"quiz"},
  ]},
  {day:"Days 74-75",label:"Behavioral + HR preparation",tasks:[
    {t:"Quiz: STAR method — prepare 5 stories: challenge, conflict, deadline, failure, leadership",k:"quiz"},
    {t:"Quiz: Tell me about yourself — 2-minute polished answer",k:"quiz"},
    {t:"Quiz: Why career switch at 33? — confident, positive framing",k:"quiz"},
    {t:"Quiz: Salary negotiation — research Hyderabad market rates for junior frontend",k:"quiz"},
  ]},
  {day:"Days 76-77",label:"Mock interviews",tasks:[
    {t:"Quiz: Do a 1-hour mock technical interview — 3 JS questions, 1 React build, 1 system design",k:"quiz"},
    {t:"Quiz: Do a 30-min behavioral mock interview",k:"quiz"},
    {t:"Quiz: Review every answer — what was weak? Study those gaps",k:"quiz"},
  ]},
  {day:"Days 78-79",label:"Job applications",tasks:[
    {t:"Code: Apply to 20+ jobs — LinkedIn Easy Apply, Naukri.com, Wellfound, company career pages",k:"code"},
    {t:"Code: Customize your resume for each job — match keywords from JD",k:"code"},
    {t:"Code: Write personalized cover letters for top 5 companies",k:"code"},
    {t:"Quiz: Research each company before interviews — product, tech stack, recent news",k:"quiz"},
  ]},
  {day:"Day 80",label:"Launch day checklist",tasks:[
    {t:"Code: All 3 portfolio projects live and bug-free",k:"code"},
    {t:"Code: GitHub profile polished — pinned repos, profile README, green contribution graph",k:"code"},
    {t:"Code: LinkedIn at All-Star strength — 500+ connections goal started",k:"code"},
    {t:"Quiz: You have built the skills. Now it is a numbers game — apply every day until you land",k:"quiz"},
  ]},
]},
];
